// utils/countryMap.js
export const countryNameToCode = {
  "Albania (Republic of)": "AL",
  "Andorra (Principality of)": "AD",
  Austria: "AT",
  Azores: "PT",
  Belgium: "BE",
  "Belarus (Republic of)": "BY",
  "Bulgaria (Republic of)": "BG",
  "Vatican City State": "VA",
  "Cyprus (Republic of)": "CY",
  "Germany (Federal Republic of)": "DE",
  Georgia: "GE",
  "Moldova (Republic of)": "MD",
  Malta: "MT",
  "Armenia (Republic of)": "AM",
  Denmark: "DK",
  Spain: "ES",
  France: "FR",
  Finland: "FI",
  "Faroe Islands": "FO",
  "United Kingdom of Great Britain and Northern Ireland": "GB",
  Gibraltar: "GI",
  Greece: "GR",
  "Croatia (Republic of)": "HR",
  "Morocco (Kingdom of)": "MA",
  "Hungary (Republic of)": "HU",
  "Netherlands (Kingdom of the)": "NL",
  Italy: "IT",
  Ireland: "IE",
  Iceland: "IS",
  "Liechtenstein (Principality of)": "LI",
  Luxembourg: "LU",
  "Monaco (Principality of)": "MC",
  Madeira: "PT",
  Norway: "NO",
  "Poland (Republic of)": "PL",
  Montenegro: "ME",
  Portugal: "PT",
  Romania: "RO",
  Sweden: "SE",
  "Slovak Republic": "SK",
  "San Marino (Republic of)": "SM",
  "Switzerland (Confederation of)": "CH",
  "Czech Republic": "CZ",
  Turkey: "TR",
  Ukraine: "UA",
  "Russian Federation": "RU",
  "The Former Yugoslav Republic of Macedonia": "MK",
  "Latvia (Republic of)": "LV",
  "Estonia (Republic of)": "EE",
  "Lithuania (Republic of)": "LT",
  "Slovenia (Republic of)": "SI",
  "Serbia (Republic of)": "RS",
  Anguilla: "AI",
  "Alaska (State of)": "US",
  "Antigua and Barbuda": "AG",
  "Netherlands Antilles": "AN", // deprecated, but kept for historical
  Aruba: "AW",
  "Bahamas (Commonwealth of the)": "BS",
  Bermuda: "BM",
  Belize: "BZ",
  Barbados: "BB",
  Canada: "CA",
  "Cayman Islands": "KY",
  "Costa Rica": "CR",
  Cuba: "CU",
  "Dominica (Commonwealth of)": "DM",
  "Dominican Republic": "DO",
  "Guadeloupe (French Department of)": "GP",
  Grenada: "GD",
  Greenland: "GL",
  "Guatemala (Republic of)": "GT",
  "Honduras (Republic of)": "HN",
  "Haiti (Republic of)": "HT",
  "United States of America": "US",
  Jamaica: "JM",
  "Saint Kitts and Nevis (Federation of)": "KN",
  "Saint Lucia": "LC",
  Mexico: "MX",
  "Martinique (French Department of)": "MQ",
  Montserrat: "MS",
  Nicaragua: "NI",
  "Panama (Republic of)": "PA",
  "-": "",
  "Puerto Rico": "PR",
  "El Salvador (Republic of)": "SV",
  "Saint Pierre and Miquelon (Territorial Collectivity of)": "PM",
  "Trinidad and Tobago": "TT",
  "Turks and Caicos Islands": "TC",
  "Saint Vincent and the Grenadines": "VC",
  "British Virgin Islands": "VG",
  "United States Virgin Islands": "VI",
  Afghanistan: "AF",
  "Saudi Arabia (Kingdom of)": "SA",
  "Bangladesh (People's Republic of)": "BD",
  "Bahrain (Kingdom of)": "BH",
  "Bhutan (Kingdom of)": "BT",
  "China (People's Republic of)": "CN",
  "Taiwan (Province of China)": "TW",
  "Sri Lanka (Democratic Socialist Republic of)": "LK",
  "India (Republic of)": "IN",
  "Iran (Islamic Republic of)": "IR",
  "Azerbaijani Republic": "AZ",
  "Iraq (Republic of)": "IQ",
  "Israel (State of)": "IL",
  Japan: "JP",
  Turkmenistan: "TM",
  "Kazakhstan (Republic of)": "KZ",
  "Uzbekistan (Republic of)": "UZ",
  "Jordan (Hashemite Kingdom of)": "JO",
  "Korea (Republic of)": "KR",
  "Palestine (In accordance with Resolution 99 Rev. Antalya, 2006)": "PS",
  "Democratic People's Republic of Korea": "KP",
  "Kuwait (State of)": "KW",
  Lebanon: "LB",
  "Kyrgyz Republic": "KG",
  "Macao (Special Administrative Region of China)": "MO",
  "Maldives (Republic of)": "MV",
  Mongolia: "MN",
  "Nepal (Federal Democratic Republic of)": "NP",
  "Oman (Sultanate of)": "OM",
  "Pakistan (Islamic Republic of)": "PK",
  "Qatar (State of)": "QA",
  "Syrian Arab Republic": "SY",
  "United Arab Emirates": "AE",
  "Yemen (Republic of)": "YE",
  "Hong Kong (Special Administrative Region of China)": "HK",
  "Bosnia and Herzegovina": "BA",
  "Adelie Land": "", // Antarctic claim, no ISO code
  Australia: "AU",
  "Myanmar (Union of)": "MM",
  "Brunei Darussalam": "BN",
  "Micronesia (Federated States of)": "FM",
  "Palau (Republic of)": "PW",
  "New Zealand": "NZ",
  "Cambodia (Kingdom of)": "KH",
  "Christmas Island (Indian Ocean)": "CX",
  "Cook Islands": "CK",
  "Fiji (Republic of)": "FJ",
  "Cocos (Keeling) Islands": "CC",
  "Indonesia (Republic of)": "ID",
  Kiribati: "KI",
  "Lao People's Democratic Republic": "LA",
  Malaysia: "MY",
  "Northern Mariana Islands (Commonwealth of the)": "MP",
  "Marshall Islands (Republic of the)": "MH",
  "New Caledonia": "NC",
  Niue: "NU",
  "Nauru (Republic of)": "NR",
  "French Polynesia": "PF",
  "Philippines (Republic of the)": "PH",
  "Papua New Guinea": "PG",
  "Pitcairn Island": "PN",
  "Solomon Islands": "SB",
  "American Samoa": "AS",
  "Samoa (Independent State of)": "WS",
  "Singapore (Republic of)": "SG",
  Thailand: "TH",
  "Tonga (Kingdom of)": "TO",
  Tuvalu: "TV",
  "Viet Nam (Socialist Republic of)": "VN",
  "Vanuatu (Republic of)": "VU",
  "Wallis and Futuna Islands": "WF",
  "South Africa (Republic of)": "ZA",
  "Angola (Republic of)": "AO",
  "Algeria (People's Democratic Republic of)": "DZ",
  "Saint Paul and Amsterdam Islands": "", // no ISO code
  "Ascension Island": "AC", // unofficial code
  "Burundi (Republic of)": "BI",
  "Benin (Republic of)": "BJ",
  "Botswana (Republic of)": "BW",
  "Central African Republic": "CF",
  "Cameroon (Republic of)": "CM",
  "Congo (Republic of the)": "CG",
  "Comoros (Union of the)": "KM",
  "Cape Verde (Republic of)": "CV",
  "Crozet Archipelago": "", // no ISO code
  "Côte d'Ivoire (Republic of)": "CI",
  "Djibouti (Republic of)": "DJ",
  "Egypt (Arab Republic of)": "EG",
  "Ethiopia (Federal Democratic Republic of)": "ET",
  Eritrea: "ER",
  "Gabonese Republic": "GA",
  Ghana: "GH",
  "Gambia (Republic of the)": "GM",
  "Guinea-Bissau (Republic of)": "GW",
  "Equatorial Guinea (Republic of)": "GQ",
  "Guinea (Republic of)": "GN",
  "Burkina Faso": "BF",
  "Kenya (Republic of)": "KE",
  "Kerguelen Islands": "", // no ISO code
  "Liberia (Republic of)": "LR",
  "Socialist People's Libyan Arab Jamahiriya": "LY",
  "Lesotho (Kingdom of)": "LS",
  "Mauritius (Republic of)": "MU",
  "Madagascar (Republic of)": "MG",
  "Mali (Republic of)": "ML",
  "Mozambique (Republic of)": "MZ",
  "Mauritania (Islamic Republic of)": "MR",
  Malawi: "MW",
  "Niger (Republic of the)": "NE",
  "Nigeria (Federal Republic of)": "NG",
  "Namibia (Republic of)": "NA",
  "Reunion (French Department of)": "RE",
  "Rwanda (Republic of)": "RW",
  "Sudan (Republic of the)": "SD",
  "Senegal (Republic of)": "SN",
  "Seychelles (Republic of)": "SC",
  "Saint Helena": "SH",
  "Somali Democratic Republic": "SO",
  "Sierra Leone": "SL",
  "Sao Tome and Principe (Democratic Republic of)": "ST",
  "Swaziland (Kingdom of)": "SZ",
  "Chad (Republic of)": "TD",
  "Togolese Republic": "TG",
  Tunisia: "TN",
  "Tanzania (United Republic of)": "TZ",
  "Uganda (Republic of)": "UG",
  "Democratic Republic of the Congo": "CD",
  "Zambia (Republic of)": "ZM",
  "Zimbabwe (Republic of)": "ZW",
  "Argentine Republic": "AR",
  "Brazil (Federative Republic of)": "BR",
  "Bolivia (Plurinational State of)": "BO",
  Chile: "CL",
  "Colombia (Republic of)": "CO",
  Ecuador: "EC",
  "Falkland Islands (Malvinas)": "FK",
  "Guiana (French Department of)": "GF",
  Guyana: "GY",
  "Paraguay (Republic of)": "PY",
  Peru: "PE",
  "Suriname (Republic of)": "SR",
  "Uruguay (Eastern Republic of)": "UY",
  "Venezuela (Bolivarian Republic of)": "VE",
};

export const countryCodeToName = Object.fromEntries(
  Object.entries(countryNameToCode).map(([name, code]) => [code, name])
);
